services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: juba
      POSTGRES_PASSWORD: juba
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-musync:/var/lib/postgresql/data
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest 
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"               # Expose le port 8090 pour accéder à Keycloak
    command: ["start-dev"]  # Spécifie la commande pour démarrer Keycloak en mode production
    volumes:
      - keycloak_data:/opt/keycloak/data  # Volume pour persistance des données


volumes:
  postgres-data-musync:
  keycloak_data: