spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: juba
    password: juba
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # ou validate, create, create-drop selon ton besoin
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9091

