spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: juba
    password: juba
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # ou validate, create, create-drop selon ton besoin
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/thread-musync"
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 9091

